spring:
  datasource:
    url: jdbc:postgresql://ep-shiny-sunset-alexg528-pooler.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_JCRnDgLG2qj1
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

logging:
  level:
    org.springframework.web: DEBUG
    tools.jackson: DEBUG

server:
  port: 8081

flickr:
  apiKey: e6017aef7bebeffc113de04efec554b4
  apiSecret: a2e10f69ece5c67c
  appKey: 72157718699655397-a36ae267891db7e7
  appSecret: 04e870e57e18c55b